# This file was generated by GoReleaser. DO NOT EDIT.
class Csv2keychain < Formula
  desc ""
  homepage ""
  version "1.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/fibbery/csv2keychain/releases/download/1.0.1/csv2keychain_1.0.1_darwin_amd64.tar.gz"
    sha256 "5b2d57229229269d78457b7bbaba08f7691a9dc43e176ba871e5fffea88cdf33"
  elsif OS.linux?
  end

  def install
    bin.install "csv2keychain"
  end
end
