# This file was generated by GoReleaser. DO NOT EDIT.
class Csv2keychain < Formula
  desc ""
  homepage ""
  version "1.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/fibbery/csv2keychain/releases/download/1.0.1/csv2keychain_1.0.1_darwin_amd64.tar.gz"
    sha256 "467a7ffcf6da75ded7a562c5f31abab4c2bd34799906f8c49fda6030142592bc"
  elsif OS.linux?
  end

  def install
    bin.install "csv2keychain"
    ...
  end
end
